services:
  rk9:
    image: ghcr.io/dogkisser/rk9:latest
    container_name: rk9

    environment:
      # Your Discord bot's token
      RK9_DISCORD_TOKEN: ""

      # Optional configuration:
      # How often, in minutes, e621 is queried for new posts.
      #RK9_CHECK_INTERVAL: 15

    volumes:
      # Where /rk9/ should store data.
      - "./data:/data"