name: release

on:
  push:
    paths:
      - pyproject.toml

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2

      - id: make-tag
        run: sed -n 's/^version *= *"\(.*\)"/tag=v\1/p' pyproject.toml >> "$GITHUB_OUTPUT"
    
      - id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1

      - uses: softprops/action-gh-release@v2
        with:
          prelease: ${{ startsWith(steps.get-latest-tag.outputs.tag, '0.') }}
          tag_name: ${{ steps.make-tag.outputs.tag }}
          generate_release_notes: true
        if: ${{ steps.get-latest-tag.outputs.tag != steps.make-tag.outputs.tag }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.get-latest-tag.outputs.tag != steps.make-tag.outputs.tag }}

      - run: |
          docker build . -t ghcr.io/dogkisser/rk9:latest
          docker push ghcr.io/dogkisser/rk9:latest
        if: ${{ steps.get-latest-tag.outputs.tag != steps.make-tag.outputs.tag }}